function key(x, y) { return `${x},${y}`; }
function inside(x, y) { return x >= 0 && x < 9 && y >= 0 && y < 10; }

class XiangqiEngine {
    constructor(roomId, players) { this.roomId = roomId; this.players = players.slice(0, 2).map((p, i) => ({ id: p.id, name: p.name, color: i === 0 ? 'red' : 'black', isOnline: true })); this.playerMap = Object.fromEntries(this.players.map(p => [p.id, p])); this.board = this._createBoard(); this.status = 'waiting'; this.turn = 'red'; this.currentTurnIndex = 0; this.lastMove = null; this.lastAction = null; this.actionLog = []; this.winner = null; this.drawReason = null; this.positionCounts = new Map(); this.quietHalfmoves = 0; this.checkStreak = { red: 0, black: 0 }; this.chaseStreak = { red: 0, black: 0 }; this.chaseTargets = { red: new Set(), black: new Set() }; }
    _createBoard() { const board = new Map(); const back = ['r', 'h', 'e', 'a', 'k', 'a', 'e', 'h', 'r']; for (let x = 0; x < 9; x++) { board.set(key(x, 0), { id: `br${x}`, type: back[x], color: 'black' }); board.set(key(x, 9), { id: `rr${x}`, type: back[x], color: 'red' }); } board.set(key(1, 2), { id: 'bc1', type: 'c', color: 'black' }); board.set(key(7, 2), { id: 'bc7', type: 'c', color: 'black' }); board.set(key(1, 7), { id: 'rc1', type: 'c', color: 'red' }); board.set(key(7, 7), { id: 'rc7', type: 'c', color: 'red' }); for (let x = 0; x < 9; x += 2) { board.set(key(x, 3), { id: `bs${x}`, type: 's', color: 'black' }); board.set(key(x, 6), { id: `rs${x}`, type: 's', color: 'red' }); } return board; }
    start() { if (this.players.length !== 2) return { success: false, message: '中国象棋需要 2 名玩家' }; this.status = 'playing'; this.turn = 'red'; this.currentTurnIndex = 0; this.board = this._createBoard(); this.positionCounts.clear(); this.quietHalfmoves = 0; this.checkStreak = { red: 0, black: 0 }; this.chaseStreak = { red: 0, black: 0 }; this.chaseTargets = { red: new Set(), black: new Set() }; this.lastMove = null; this.winner = null; this.drawReason = null; this._recordPosition(); this.actionLog = [`${this.players[0].name} 执红，请开始走棋`]; return this._success('中国象棋开始'); }
    handleAction(playerId, action = {}) { if (this.status !== 'playing') return { success: false, message: '棋局尚未开始或已结束' }; const player = this.playerMap[playerId]; if (!player || !player.isOnline) return { success: false, message: '玩家不存在或已离线' }; if (player.color !== this.turn) return { success: false, message: '还没轮到你', state: this.getPlayerState(playerId) }; const from = this._coord(action.from), to = this._coord(action.to); const piece = from && this.board.get(key(from.x, from.y)); if (action.kind !== 'move' || !from || !to) return { success: false, message: '请提交有效走棋', state: this.getPlayerState(playerId) }; if (!piece || piece.color !== this.turn) return { success: false, message: '只能移动自己的棋子', state: this.getPlayerState(playerId) }; const move = this._legalMoves(piece).find(m => m.to.x === to.x && m.to.y === to.y); if (!move) return { success: false, message: '这步不符合中国象棋规则', state: this.getPlayerState(playerId) }; const captured = this.board.get(key(to.x, to.y)); this._applyMove(this.board, move); this.quietHalfmoves = captured ? 0 : this.quietHalfmoves + 1; this.lastMove = { from, to, piece: { ...piece }, capture: captured || null }; this.lastAction = { kind: 'move', playerId, playerName: player.name, message: `${player.name} 移动了${this._name(piece.type)}` }; this.actionLog.push(this.lastAction.message); this.turn = this.turn === 'red' ? 'black' : 'red'; this.currentTurnIndex = this.turn === 'red' ? 0 : 1; const checkingPieceIds = this._checkingPieces(this.turn, this.board); const gaveCheck = checkingPieceIds.length > 0; const chaseTargets = this._chaseTargets(piece.color, this.board); const previousChase = this.chaseTargets[piece.color]; this.lastMove.gaveCheck = gaveCheck; this.lastMove.checkingPieceIds = checkingPieceIds; this.lastMove.chaseTargets = [...chaseTargets]; this.checkStreak[piece.color] = gaveCheck ? this.checkStreak[piece.color] + 1 : 0; this.lastMove.checkCount = this.checkStreak[piece.color]; this.lastMove.longCheckWarning = gaveCheck && this.checkStreak[piece.color] >= 2; if (gaveCheck && this.checkStreak[piece.color] === 2) this.actionLog.push(`${player.name} 已连续将军 2 次；若再次形成同一重复局面，长将方判负`); this.chaseStreak[piece.color] = chaseTargets.size ? (previousChase && [...chaseTargets].some(target => previousChase.has(target)) ? this.chaseStreak[piece.color] + 1 : 1) : 0; this.chaseTargets[piece.color] = chaseTargets; this._recordPosition(); this._evaluate(); return this._success(this.lastAction.message); }
    _coord(v) { return v && Number.isInteger(v.x) && Number.isInteger(v.y) && inside(v.x, v.y) ? { x: v.x, y: v.y } : null; }
    _name(type) { return ({ k: '将/帅', a: '士', e: '象', h: '马', r: '车', c: '炮', s: '兵/卒' })[type] || '棋子'; }
    _legalMoves(piece) { const from = this._findPiece(piece.id, this.board); if (!from) return []; return this._pseudo(piece, from, this.board).filter(move => this.board.get(key(move.to.x, move.to.y))?.type !== 'k').filter(move => { const simulated = this._clone(this.board); this._applyMove(simulated, move); return !this._inCheck(piece.color, simulated); }); }
    _pseudo(piece, from, board) { const moves = []; const add = (x, y) => { if (!inside(x, y)) return false; const target = board.get(key(x, y)); if (target?.color === piece.color) return false; moves.push({ from: { ...from }, to: { x, y }, capture: Boolean(target) }); return !target; };
        if (piece.type === 'k') { const palace = piece.color === 'red' ? [7, 9] : [0, 2]; [[1, 0], [-1, 0], [0, 1], [0, -1]].forEach(([dx, dy]) => { const x = from.x + dx, y = from.y + dy; if (x >= 3 && x <= 5 && y >= palace[0] && y <= palace[1]) add(x, y); }); const dir = piece.color === 'red' ? -1 : 1; let y = from.y + dir; while (inside(from.x, y) && !board.has(key(from.x, y))) y += dir; const target = board.get(key(from.x, y)); if (target?.type === 'k' && target.color !== piece.color) moves.push({ from: { ...from }, to: { x: from.x, y }, capture: true }); }
        else if (piece.type === 'a') { const palace = piece.color === 'red' ? [7, 9] : [0, 2]; [[1, 1], [1, -1], [-1, 1], [-1, -1]].forEach(([dx, dy]) => { const x = from.x + dx, y = from.y + dy; if (x >= 3 && x <= 5 && y >= palace[0] && y <= palace[1]) add(x, y); }); }
        else if (piece.type === 'e') { [[2, 2], [2, -2], [-2, 2], [-2, -2]].forEach(([dx, dy]) => { const x = from.x + dx, y = from.y + dy, mid = key(from.x + dx / 2, from.y + dy / 2); const ownSide = piece.color === 'red' ? y >= 5 : y <= 4; if (ownSide && !board.has(mid)) add(x, y); }); }
        else if (piece.type === 'h') { [[1, 2, 0, 1], [2, 1, 1, 0], [-1, 2, 0, 1], [-2, 1, -1, 0], [1, -2, 0, -1], [2, -1, 1, 0], [-1, -2, 0, -1], [-2, -1, -1, 0]].forEach(([dx, dy, lx, ly]) => { if (!board.has(key(from.x + lx, from.y + ly))) add(from.x + dx, from.y + dy); }); }
        else if (piece.type === 'r') this._slide(piece, from, board, moves, false);
        else if (piece.type === 'c') this._slide(piece, from, board, moves, true);
        else if (piece.type === 's') { const dir = piece.color === 'red' ? -1 : 1; add(from.x, from.y + dir); const crossed = piece.color === 'red' ? from.y <= 4 : from.y >= 5; if (crossed) { add(from.x - 1, from.y); add(from.x + 1, from.y); } }
        return moves;
    }
    _slide(piece, from, board, moves, cannon) { for (const [dx, dy] of [[1, 0], [-1, 0], [0, 1], [0, -1]]) { let x = from.x + dx, y = from.y + dy, screen = false; while (inside(x, y)) { const target = board.get(key(x, y)); if (!screen && !target) { moves.push({ from: { ...from }, to: { x, y } }); x += dx; y += dy; continue; } if (!cannon) { if (target?.color !== piece.color) moves.push({ from: { ...from }, to: { x, y }, capture: Boolean(target) }); break; } if (!screen) { screen = true; x += dx; y += dy; continue; } if (target) { if (target.color !== piece.color) moves.push({ from: { ...from }, to: { x, y }, capture: true }); break; } x += dx; y += dy; } } }
    _applyMove(board, move) { const piece = board.get(key(move.from.x, move.from.y)); if (!piece) return; board.delete(key(move.from.x, move.from.y)); board.set(key(move.to.x, move.to.y), piece); }
    _clone(board) { return new Map([...board].map(([pos, piece]) => [pos, { ...piece }])); }
    _findPiece(id, board) { for (const [pos, p] of board) if (p.id === id) { const [x, y] = pos.split(',').map(Number); return { x, y }; } return null; }
    _checkingPieces(color, board) { const king = [...board.entries()].find(([, p]) => p.color === color && p.type === 'k'); if (!king) return []; const [x, y] = king[0].split(',').map(Number); const opponent = color === 'red' ? 'black' : 'red'; const checking = new Set(); for (const [pos, p] of board) { if (p.color !== opponent) continue; const [px, py] = pos.split(',').map(Number); if (p.type === 'k' && px === x) { let clear = true; for (let cy = Math.min(py, y) + 1; cy < Math.max(py, y); cy++) if (board.has(key(x, cy))) clear = false; if (clear) checking.add(p.id); } if (this._pseudo(p, { x: px, y: py }, board).some(m => m.to.x === x && m.to.y === y)) checking.add(p.id); } return [...checking]; }
    _inCheck(color, board) { const hasKing = [...board.values()].some(piece => piece.color === color && piece.type === 'k'); return !hasKing || this._checkingPieces(color, board).length > 0; }
    _chaseTargets(color, board) { const targets = new Set(); for (const [pos, piece] of board) { if (piece.color !== color) continue; const [x, y] = pos.split(',').map(Number); for (const move of this._pseudo(piece, { x, y }, board)) { const target = board.get(key(move.to.x, move.to.y)); if (!target || target.color === color || target.type === 'k') continue; if (!this._isProtected(target, board)) targets.add(target.id); } } return targets; }
    _isProtected(target, board) { const targetPos = [...board.entries()].find(([, piece]) => piece.id === target.id)?.[0]; if (!targetPos) return false; const [x, y] = targetPos.split(',').map(Number); return [...board.entries()].some(([pos, piece]) => { if (piece.color !== target.color || piece.id === target.id) return false; const [px, py] = pos.split(',').map(Number); return this._pseudo(piece, { x: px, y: py }, board).some(move => move.to.x === x && move.to.y === y); }); }
    _positionKey() { return `${this.turn}|${[...this.board.entries()].map(([position, piece]) => `${position}:${piece.color[0]}${piece.type}`).sort().join('/')}`; }
    _recordPosition() { const position = this._positionKey(); this.positionCounts.set(position, (this.positionCounts.get(position) || 0) + 1); }
    _evaluate() { const moves = [...this.board.values()].filter(p => p.color === this.turn).flatMap(p => this._legalMoves(p)); if (!moves.length) { this.status = 'ended'; if (this._inCheck(this.turn, this.board)) this.winner = this.players.find(p => p.color !== this.turn) || null; else { this.winner = this.players.find(p => p.color === (this.turn === 'red' ? 'black' : 'red')) || null; this.actionLog.push('困毙，无法行动的一方判负'); } return; } const repetitions = this.positionCounts.get(this._positionKey()) || 0; if (repetitions >= 3) { const checkingColor = this.lastMove?.piece?.color; if (checkingColor && this.checkStreak[checkingColor] >= 3) { this.status = 'ended'; this.winner = this.players.find(p => p.color !== checkingColor) || null; this.actionLog.push(`${this.winner?.name || '对手'} 因对方长将获胜`); return; } if (checkingColor && this.chaseStreak[checkingColor] >= 3) { this.status = 'ended'; this.winner = this.players.find(p => p.color !== checkingColor) || null; this.actionLog.push(`${this.winner?.name || '对手'} 因对方长捉获胜`); return; } this.status = 'ended'; this.drawReason = '三次重复局面和棋'; this.actionLog.push(this.drawReason); return; } if (this.quietHalfmoves >= 120) { this.status = 'ended'; this.drawReason = '六十回合无吃子和棋'; this.actionLog.push(this.drawReason); } }
    getPublicState() { const warningColor = this.lastMove?.gaveCheck && this.lastMove.checkCount >= 2 ? this.lastMove.piece.color : null; const warningPlayer = warningColor ? this.players.find(player => player.color === warningColor) : null; return { roomId: this.roomId, status: this.status, turn: this.turn, currentTurn: this.players[this.currentTurnIndex]?.id || null, currentTurnName: this.players[this.currentTurnIndex]?.name || null, check: this._inCheck(this.turn, this.board), players: this.players.map(p => ({ id: p.id, name: p.name, color: p.color, isOnline: p.isOnline, isCurrentTurn: p.color === this.turn })), pieces: [...this.board.entries()].map(([pos, p]) => { const [x, y] = pos.split(',').map(Number); return { ...p, x, y }; }), lastMove: this.lastMove, lastAction: this.lastAction, actionLog: this.actionLog.slice(-14), drawReason: this.drawReason, quietHalfmoves: this.quietHalfmoves, checkStreak: { ...this.checkStreak }, chaseStreak: { ...this.chaseStreak }, repetitionCount: this.positionCounts.get(this._positionKey()) || 0, longCheckWarning: warningColor ? { color: warningColor, playerId: warningPlayer?.id || null, playerName: warningPlayer?.name || '', count: this.lastMove.checkCount, message: `${warningPlayer?.name || (warningColor === 'red' ? '红方' : '黑方')} 已连续将军 ${this.lastMove.checkCount} 次；再次形成三次重复局面，长将方判负` } : null, winner: this.winner ? { id: this.winner.id, name: this.winner.name, color: this.winner.color } : null }; }
    getPlayerState(playerId) { const state = this.getPublicState(); const player = this.playerMap[playerId]; state.myId = playerId; state.myColor = player?.color || null; state.myIsCurrentTurn = state.currentTurn === playerId; state.legalMoves = {}; if (player?.color === this.turn && this.status === 'playing') for (const p of this.board.values()) if (p.color === player.color) state.legalMoves[p.id] = this._legalMoves(p).map(m => m.to); state.availableActions = { canMove: state.myIsCurrentTurn && this.status === 'playing' }; return state; }
    handlePlayerLeave(playerId) { const p = this.playerMap[playerId]; if (!p) return { success: false, message: '玩家不存在' }; p.isOnline = false; if (this.status === 'playing') { this.status = 'ended'; this.winner = this.players.find(other => other.id !== playerId && other.isOnline) || null; } return this._success(`${p.name} 离开棋局`); }
    _success(message) { return { success: true, message, state: this.getPublicState(), ended: this.status === 'ended', winner: this.winner ? { id: this.winner.id, name: this.winner.name } : null }; }
    getWinner() { return this.winner ? { id: this.winner.id, name: this.winner.name } : null; }
}
module.exports = XiangqiEngine;
